[package]
name = "witcher-track"
version = "0.1.0"
edition = "2021"

[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "9d47b24"

[package.metadata.vcpkg.target.'x86_64-pc-windows-msvc']
triplet = "x64-windows-static-md"
dependencies = ["leptonica", "tesseract"]

[dependencies]
anyhow = "1.0.72"
lazy_static = "1.4.0"
leptonica-sys = "0.4.5"
screenshots = "0.7.0"
tesseract-sys = "0.6.0"
ureq = "2.7.1"
windows = { version = "0.48.0", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation"] }
