[package]
name = "witcher-save"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.72"
lz4 = "1.24.0"
lz4_flex = "0.11.1"
